2020-12-09T11:06:03.2738646+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-12-09T11:06:03.2891094+02:00  [INF] Now listening on: "http://localhost:5002" (d826f4b8)
2020-12-09T11:06:03.2992448+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-12-09T11:06:03.3015721+02:00  [INF] Hosting environment: "Development" (c3307c92)
2020-12-09T11:06:03.3045919+02:00  [INF] Content root path: "D:\Applications\SuperStore\src\Web\WebApi" (b5d60022)
2020-12-09T11:15:07.0176036+02:00 0HM4S46JPGFL9:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at WebApi.Controllers.ProductController.UploadImage(IFormFile file) in D:\Applications\SuperStore\src\Web\WebApi\Controllers\ProductController.cs:line 55
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-12-09T11:16:52.8672992+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-12-09T11:16:52.8777403+02:00  [INF] Now listening on: "http://localhost:5002" (d826f4b8)
2020-12-09T11:16:52.8802415+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-12-09T11:16:52.8856711+02:00  [INF] Hosting environment: "Development" (c3307c92)
2020-12-09T11:16:52.8908355+02:00  [INF] Content root path: "D:\Applications\SuperStore\src\Web\WebApi" (b5d60022)
2020-12-09T11:17:22.6989778+02:00 0HM4S4CLEMQUM:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at WebApi.Controllers.ProductController.UploadImage(IFormFile file) in D:\Applications\SuperStore\src\Web\WebApi\Controllers\ProductController.cs:line 55
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-12-09T11:17:57.4528321+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-12-09T11:17:57.4611738+02:00  [INF] Now listening on: "http://localhost:5002" (d826f4b8)
2020-12-09T11:17:57.4645603+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-12-09T11:17:57.4700122+02:00  [INF] Hosting environment: "Development" (c3307c92)
2020-12-09T11:17:57.4735342+02:00  [INF] Content root path: "D:\Applications\SuperStore\src\Web\WebApi" (b5d60022)
2020-12-09T11:19:31.4280130+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-12-09T11:19:31.4462594+02:00  [INF] Now listening on: "http://localhost:5002" (d826f4b8)
2020-12-09T11:19:31.4502755+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-12-09T11:19:31.4566103+02:00  [INF] Hosting environment: "Development" (c3307c92)
2020-12-09T11:19:31.4636811+02:00  [INF] Content root path: "D:\Applications\SuperStore\src\Web\WebApi" (b5d60022)
2020-12-09T11:19:51.4769516+02:00 0HM4S4E4NG16P:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at WebApi.Controllers.ProductController.UploadImage(IFormFile file) in D:\Applications\SuperStore\src\Web\WebApi\Controllers\ProductController.cs:line 55
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-12-09T11:35:13.2769984+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-12-09T11:35:13.3055974+02:00  [INF] Now listening on: "http://localhost:5002" (d826f4b8)
2020-12-09T11:35:13.3081103+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-12-09T11:35:13.3100849+02:00  [INF] Hosting environment: "Development" (c3307c92)
2020-12-09T11:35:13.3132560+02:00  [INF] Content root path: "D:\Applications\SuperStore\src\Web\WebApi" (b5d60022)
